name: okru_oauth
description: okru auth library
version: 1.0.2
repository: "https://github.com/Olifemus/okru_oauth"

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3

flutter:
  plugin:
    platforms:
      android:
        package: com.eegorov.okru_oauth
        pluginClass: OkruOauthPlugin
      ios:
        pluginClass: OkruOauthPlugin
